repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.5
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      exclude: _vendored
    - id: ruff-format
      exclude: _vendored