[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
select = [
    "E", "F", # default
    "I", # isort
]

[tool.ruff.isort]
known-first-party = ["pwfluo"]
known-third-party = ["pyworkflow"]